### ISSUE TITLE
Adding monoRTM as a git submodule

### ISSUE THREAD

**Issue by StegmannJCSDA** [AER-RC/monoRTM#4]
Hello Rick @pernak18 and @kcadyper. We would like to track both `AER-RC/monoRTM` and `AER-RC/LBLRTM` as git submodules in the CRTM coefficient generation repository and so I wanted to ask which branch we should track for this purpose.

**Comment by pernak18** [comment]
hi @StegmannJCSDA. awesome! i would suggest, instead of doing a `checkout` of a specific branch, doing a `checkout` of a specific release for a given model. i'm not sure if there are CRTM compatibility issues with newer versions of LBL and monoRTM, but the latest releases are [v12.11](https://github.com/AER-RC/LBLRTM/releases/tag/v12.11) and [v5.6](https://github.com/AER-RC/monoRTM/releases/tag/v5.6), respectively. monoRTM v5.6 is very new.

if there are problems with CRTM and these newer versions, we have LBL v12.9 and v12.10 in GitHub and v5.5 of monoRTM. all releases before v12.9 and v5.5 are not in Git.

but if you always want the "bleeding edge" of these models, perhaps tracking with `master` is the way to go.

**Comment by StegmannJCSDA** [comment]
Thank you. I have added monoRTM `tags/v5.6` as a submodule for now. We will probably follow the most recent releases later on.
